# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InspectorExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InspectorExample
 pod 'mParticle-Apple-SDK'
 pod 'mParticle-Apple-Inspector', :path => '../../'

 target 'InspectorExampleTests' do
   	inherit! :search_paths
   	# Pods for testing
 	pod 'mParticle-Apple-SDK'
	pod 'mParticle-Apple-Inspector', :path => '../../'
 end

end
